# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Distribute to Firebase App Distribution"
    lane :distribute_to_firebase do
      gradle(task: "clean assembleRelease")
      firebase_app_distribution(
        debug: true,
        app: "1:910789066360:android:4a97fd5c9a0f8f4a80378d",
#         testers: "user@email.com",
        groups: "qa",
        release_notes: "New release for the QA team",
        service_credentials_file: "fastlane/saborify-bd18e-4b3a931364d3.json"
      )
    end
end
