# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    desc "Runs all the tests"
    lane :test do
        gradle(task: "test")
    end

    desc "Submit a new Beta Build to Crashlytics Beta"
    lane :beta do
        gradle(task: "clean assembleRelease")
        crashlytics

        # sh "your_script.sh"
        # You can also use other beta testing services here
    end

    desc "Deploy a new version to the Google Play"
    lane :deploy do
        gradle(task: "clean assembleRelease")
        upload_to_play_store
    end

    desc "Distribute Saborify to Firebase App Distribution"
    lane :distribute_saborify_to_firebase do
        gradle(task: "clean assembleSaborifyRelease")
        firebase_app_distribution(
            debug: true,
            app: "1:168680760801:android:2f3e3f38e01e5482711ea0",
            groups: "qa",
            release_notes: "New release for the QA team",
            service_credentials_file: "fastlane/saborify-ad712-c5d44772f932.json"
        )
    end

    desc "Distribute Blank to Firebase App Distribution"
    lane :distribute_blank_to_firebase do
        gradle(task: "clean assembleBlankRelease")
        firebase_app_distribution(
            debug: true,
            app: "1:1089739619010:android:450e7897f96e8eb318595b",
            groups: "qa",
            release_notes: "New release for the QA team",
            service_credentials_file: "fastlane/blank-2315c-60baf82c1a04.json"
        )
    end

    desc "Distribute all flavors to Firebase App Distribution"
    lane :distribute_all_flavors_to_firebase do
        distribute_saborify_to_firebase
        distribute_blank_to_firebase
    end
end
